"""Initial migration - all models

Revision ID: db6d1def3135
Revises: 
Create Date: 2026-07-06 16:28:50.470898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6d1def3135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_booking_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_discount_cap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)

    op.create_table('destinations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gallery_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('package', 'destination', 'hotel', name='gallery_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_images_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_images_entity_type'), ['entity_type'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('guest', 'customer', 'scout', 'driver', 'vendor', 'hotel_partner', 'admin', 'super_admin', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_entity', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_entity'), ['target_entity'], unique=False)

    op.create_table('blog_posts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='blog_post_status_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_posts_status'), ['status'], unique=False)

    op.create_table('drivers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('operating_area', sa.Enum('varanasi', 'mirzapur', name='operating_area_enum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_assignments', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_operating_area'), ['operating_area'], unique=False)

    op.create_table('enterprise_bookings',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('travel_start_date', sa.Date(), nullable=False),
    sa.Column('travel_end_date', sa.Date(), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'quotation_sent', 'confirmed', 'in_progress', 'completed', 'cancelled', name='enterprise_booking_status_enum'), nullable=False),
    sa.Column('quotation', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_bookings_customer_id'), ['customer_id'], unique=False)

    op.create_table('hotels',
    sa.Column('partner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_partner_user_id'), ['partner_user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_channel', sa.Enum('in_app', 'email', name='delivery_channel_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('packages',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('traveller_type', sa.Enum('solo', 'couple', 'family', 'group', 'corporate', name='traveller_type_enum'), nullable=False),
    sa.Column('inclusions', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_packages_traveller_type'), ['traveller_type'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('scouts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('operating_area', sa.Enum('varanasi', 'mirzapur', name='operating_area_enum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_assignments', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scouts_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_scouts_operating_area'), ['operating_area'], unique=False)

    op.create_table('sub_destinations',
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('category', sa.Enum('ghat', 'temple', 'waterfall', 'hidden_place', 'market', 'food_spot', 'cultural_site', name='sub_destination_category'), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_destinations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_destinations_destination_id'), ['destination_id'], unique=False)

    op.create_table('driver_availabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'date', name='uq_driver_availability_date')
    )
    with op.batch_alter_table('driver_availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_availabilities_driver_id'), ['driver_id'], unique=False)

    op.create_table('itineraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'day_number', name='uq_itinerary_package_day')
    )
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itineraries_package_id'), ['package_id'], unique=False)

    op.create_table('pricing_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('tier_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_persons', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'tier_name', name='uq_pricing_tier_package_tier')
    )
    with op.batch_alter_table('pricing_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_tiers_package_id'), ['package_id'], unique=False)

    op.create_table('room_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hotel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_types_hotel_id'), ['hotel_id'], unique=False)

    op.create_table('scout_availabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scout_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scout_id'], ['scouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scout_id', 'date', name='uq_scout_availability_date')
    )
    with op.batch_alter_table('scout_availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scout_availabilities_scout_id'), ['scout_id'], unique=False)

    op.create_table('wishlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'package_id', name='uq_customer_package_wishlist')
    )
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlists_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlists_package_id'), ['package_id'], unique=False)

    op.create_table('bookings',
    sa.Column('booking_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_payment', 'confirmed', 'in_progress', 'completed', 'cancelled', 'refunded', name='booking_status_enum'), nullable=False),
    sa.Column('travel_start_date', sa.Date(), nullable=False),
    sa.Column('travel_end_date', sa.Date(), nullable=False),
    sa.Column('num_travellers', sa.Integer(), nullable=False),
    sa.Column('traveller_type', sa.String(length=50), nullable=False),
    sa.Column('hotel_preference_id', sa.String(length=36), nullable=True),
    sa.Column('room_type_id', sa.String(length=36), nullable=True),
    sa.Column('transport_preferences', sa.JSON(), nullable=True),
    sa.Column('add_ons', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('coupon_id', sa.String(length=36), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hotel_preference_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_number'), ['booking_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('room_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_type_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('available_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type_id', 'date', name='uq_room_availability_type_date')
    )
    with op.batch_alter_table('room_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_availability_room_type_id'), ['room_type_id'], unique=False)

    op.create_table('booking_drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'driver_id', name='uq_booking_driver')
    )
    with op.batch_alter_table('booking_drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_drivers_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_drivers_driver_id'), ['driver_id'], unique=False)

    op.create_table('booking_scouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('scout_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['scout_id'], ['scouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'scout_id', name='uq_booking_scout')
    )
    with op.batch_alter_table('booking_scouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_scouts_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_scouts_scout_id'), ['scout_id'], unique=False)

    op.create_table('booking_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_status_history_booking_id'), ['booking_id'], unique=False)

    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('payments',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='payment_status_enum'), nullable=False),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_gateway_transaction_id'), ['gateway_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('reviews',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('package', 'scout', 'driver', name='review_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending_moderation', 'published', 'rejected', name='review_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_status'), ['status'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticket_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)

    op.create_table('refunds',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='refund_status_enum'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_status'), ['status'], unique=False)

    op.create_table('ticket_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_replies_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_replies_ticket_id'))

    op.drop_table('ticket_replies')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_status'))
        batch_op.drop_index(batch_op.f('ix_refunds_payment_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_booking_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_customer_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_booking_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_reviews_package_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_entity_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_customer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_booking_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_booking_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_booking_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('booking_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_status_history_booking_id'))

    op.drop_table('booking_status_history')
    with op.batch_alter_table('booking_scouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_scouts_scout_id'))
        batch_op.drop_index(batch_op.f('ix_booking_scouts_booking_id'))

    op.drop_table('booking_scouts')
    with op.batch_alter_table('booking_drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_drivers_driver_id'))
        batch_op.drop_index(batch_op.f('ix_booking_drivers_booking_id'))

    op.drop_table('booking_drivers')
    with op.batch_alter_table('room_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_availability_room_type_id'))

    op.drop_table('room_availability')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_package_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_number'))

    op.drop_table('bookings')
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlists_package_id'))
        batch_op.drop_index(batch_op.f('ix_wishlists_customer_id'))

    op.drop_table('wishlists')
    with op.batch_alter_table('scout_availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scout_availabilities_scout_id'))

    op.drop_table('scout_availabilities')
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_types_hotel_id'))

    op.drop_table('room_types')
    with op.batch_alter_table('pricing_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_tiers_package_id'))

    op.drop_table('pricing_tiers')
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itineraries_package_id'))

    op.drop_table('itineraries')
    with op.batch_alter_table('driver_availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_availabilities_driver_id'))

    op.drop_table('driver_availabilities')
    with op.batch_alter_table('sub_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_destinations_destination_id'))
        batch_op.drop_index(batch_op.f('ix_sub_destinations_category'))

    op.drop_table('sub_destinations')
    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scouts_operating_area'))
        batch_op.drop_index(batch_op.f('ix_scouts_is_available'))

    op.drop_table('scouts')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_traveller_type'))
        batch_op.drop_index(batch_op.f('ix_packages_slug'))
        batch_op.drop_index(batch_op.f('ix_packages_is_active'))
        batch_op.drop_index(batch_op.f('ix_packages_destination_id'))

    op.drop_table('packages')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_partner_user_id'))
        batch_op.drop_index(batch_op.f('ix_hotels_destination_id'))

    op.drop_table('hotels')
    with op.batch_alter_table('enterprise_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_bookings_customer_id'))

    op.drop_table('enterprise_bookings')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_operating_area'))
        batch_op.drop_index(batch_op.f('ix_drivers_is_available'))

    op.drop_table('drivers')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_status'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_category'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_author_id'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('ix_users_deleted_at')

    op.drop_table('users')
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_images_entity_type'))
        batch_op.drop_index(batch_op.f('ix_gallery_images_entity_id'))

    op.drop_table('gallery_images')
    op.drop_table('destinations')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    # ### end Alembic commands ###
